### ISSUE TITLE
Initial Pseudo Label Link Failure

### ISSUE THREAD

**Issue by breezezero** [xmed-lab/CPR#5]
Dear researcher, this initial pseudo label seems to be invalid, can you re-share it?

**Comment by zheangh** [comment]
Hello @breezezero ,

Sorry for the inconvenience. I have uploaded the initial pseudo label and the refined pseudo label again. Please download them with the following links:
[The initial pseudo label](https://drive.google.com/file/d/16bcSGOCdcD3l-_Csu3tvc_CfFBfcbcca/view?usp=sharing)
[The refined pseudo label](https://drive.google.com/file/d/1leUgZhvuai_V1Tj8IMUK3TPqn3604sOS/view?usp=sharing)

**Comment by breezezero** [comment]
Thank you
